model_params:
  name:                   'affordance'
  input_dim:              256
  output_dim:             2
  n_image:                4

train_params:
  batch_size:             32
  n_epochs:               50
  optimizer:
    type:                 'Adam'
    learning_rate:        0.00005
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234
  lr_scheduler:
    enable:               False
    step_size:            10
    gamma:                0.5

log_params:
  name:                   'affordance'
  log_interval:           5
  checkpoint_preload:     True
  use_tensorboard:        True