model_params:
  name:                   'affordance_ctrl'
  input_dim:              3
  with_yawRate:           False

train_params:
  batch_size:             32
  n_epochs:               100
  optimizer:
    type:                 'Adam'
    learning_rate:        0.0005
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234
  lr_scheduler:
    enable:               False
    step_size:            10
    gamma:                0.5

log_params:
  name:                   'affordance_ctrl'
  log_interval:           10
  checkpoint_preload:     False
  use_tensorboard:        True