model_params:
  name:                   'latent_fc'
  in_channels:            3
  with_yawRate:           False

train_params:
  batch_size:             256
  n_epochs:               100
  optimizer:
    type:                 'Adam'
    learning_rate:        0.00005
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234
  lr_scheduler:
    enable:               False
    step_size:            50
    gamma:                0.5
    
log_params:
  name:                   'latent_fc'
  log_interval:           10
  checkpoint_preload:     False
  use_tensorboard:        True