model_params:
  name:                   'latent_ctrl'
  z_dim:                  1000
  extra_dim:              6
  enable_extra:           False

train_params:
  batch_size:             128
  n_epochs:               500
  optimizer:
    type:                 'Adam'
    learning_rate:        0.0001
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234
  lr_scheduler:
    enable:               False
    step_size:            50
    gamma:                0.5
    
log_params:
  name:                   'latent_ctrl'
  log_interval:           10
  checkpoint_preload:     True
  use_tensorboard:        True