## Global parameters
path_params:
  dataset_dir:                '/media/lab/NEPTUNE2/field_datasets/row_4_10_13' # source datasets directory
  output_dir:                 '/media/lab/NEPTUNE2/field_outputs/row_4_10_13' # save output to this directory
  extra_dataset_dir:          '/media/lab/NEPTUNE2/field_datasets/vae_extra' # extra datasets directory

## Train parameters
train_params:  
  device:                     'cuda:0' # {'cuda:idx', 'cpu'} torch device

# Affordance
affordance_params:
  image_resize:               [256, 256] # resize image

# VAE
vae_params:
  vae_type:                   'vanilla_vae'

# Latent Ctrl
latentCtrl_params:
  vae_model_path:             '/media/lab/NEPTUNE2/field_outputs/imitation_learning/vanilla_vae/vanilla_vae_model_z_1000.pt' # VAE model file path

## Dataset parameters
dataset_params:
  test_size:                  0.0 # [0,1] of the total data
  random_state:               1234 # random seed
  iteration:                  3 # dagger iteration