model_params:
  name:                   'vanilla_vae'
  in_channels:            3
  z_dim:                  1000
  input_dim:              128

train_params:
  batch_size:             128
  n_epochs:               50
  optimizer:
    type:                 'Adam'
    learning_rate:        0.00001
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234
  lr_scheduler:
    enable:               False
    step_size:            50
    gamma:                0.5

log_params:
  name:                   'vanilla_vae'
  log_interval:           10
  checkpoint_preload:     True
  generate_samples:       True
  use_tensorboard:        True