## Global parameters
path_params:
  dataset_dir:                '/media/lab/Hard Disk/my_datasets/longmap1' # source datasets directory
  output_dir:                 '/media/lab/Hard Disk/my_outputs/longmap1' # save output to this directory

## Train parameters
train_params:  
  device:                     'cuda:0' # {'cuda:idx', 'cpu'} torch device

# Affordance
affordance_params:
  image_resize:               [256, 256] # resize image
  map_name:                   'longmap1' # map name

# Affordance Ctrl
affordanceCtrl_params:
  image_resize:               [256, 256] # resize image
  model_path:                 '/media/lab/Hard Disk/my_outputs/longmap1/affordance/affordance_model.pt'
  map_name:                   'longmap1'

## Dataset parameters
dataset_params:
  test_size:                  0.0 # [0,1] of the total data
  random_state:               11 # random seed