plugin_blacklist:
# common
- safety_area
# extras
- image_pub
- vibration
# distance_sensor
- rangefinder
- wheel_odometry
- mocap
- vibration 
- px4flow
- landing_target
- wind_estimation
- fake_gps
- camera


plugin_whitelist: []
#- 'sys_*'
