plugin_blacklist:
- adsb
- camera
- cam_imu_sync
- debug_value
- fake_gps
- geofence
- hil
- image_pub
- landing_target
- log_transfer
- mocap_pose_estimate
- obstacle_distance
- px4flow
- rangefinder
- safety_area
- terrain
- tunnel
- vibration
- vfr_hud
- wheel_odometry
- wind_estimation

plugin_whitelist: []
#- 'sys_*'
